package com.app.examprep.fragment

import android.os.Bundle
import android.view.View
import androidx.fragment.app.Fragment
import com.app.examprep.R
import com.app.examprep.databinding.FragmentTncBinding

class PrivacyPolicyFragment: Fragment(R.layout.fragment_tnc) {


    lateinit var binding : FragmentTncBinding
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)


        binding = FragmentTncBinding.bind(view)


        setUI(view)


    }

    private fun setUI(view: View) {

        binding.tvTitle.text = "Privacy Policy"
        binding.tvNotes.text = "This Privacy Policy describes Our policies and procedures on\n" +
                "the collection, use and disclosure of Your information when\n" +
                "You use the Service and tells You about Your privacy rights\n" +
                "and how the law protects You.\n" +
                "We use Your Personal data to provide and improve the\n" +
                "Service. By using the Service, You agree to the collection and\n" +
                "use of information in accordance with this Privacy Policy.\n" +
                "Interpretation and Definitions Interpretation The words of\n" +
                "which the initial letter is capitalized have meanings defined\n" +
                "under the following conditions.\n" +
                "The following definitions shall have the same meaning\n" +
                "regardless of whether they appear in singular or in plural.\n" +
                "Definitions For the purposes of this Privacy Policy:\n" +
                "You means the individual accessing or using the Service, or\n" +
                "the company, or other legal entity on behalf of which such\n" +
                "individual is accessing or using the Service, as applicable.\n" +
                "Company (referred to as either “the Company”, “We”, “Us” or\n" +
                "“Our” in this Agreement) refers to vidhyasoft.com\n" +
                "Affiliate means an entity that controls, is controlled by or is\n" +
                "under common control with a party, where “control” means\n" +
                "ownership of 50% or more of the shares, equity interest or\n" +
                "other securities entitled to vote for election of directors or\n" +
                "other managing authority. Account means a unique account\n" +
                "created for You to access our Service or parts of our Service.\n" +
                "Website refers to vidhyasoft.com, accessible from\n" +
                "vidhyasoft.com Service refers to the Website. Country refers\n" +
                "to: Telangana, India.\n" +
                "Service Provider means any natural or legal person who\n" +
                "processes the data on behalf of the Company. It refers to\n" +
                "third-party companies or individuals employed by the\n" +
                "Company to facilitate the Service, to provide the Service on\n" +
                "behalf of the Company, to perform services related to the\n" +
                "Service or to assist the Company in analyzing how the\n" +
                "Service is used. Third-party Social Media Service refers to\n" +
                "any website or any social network website through which a\n" +
                "User can log in or create an account to use the Service.\n" +
                "Personal Data is any information that relates to an identified\n" +
                "or identifiable individual. Cookies are small files that are\n" +
                "placed on Your computer, mobile device or any other device\n" +
                "by a website, containing the details of Your browsing history\n" +
                "on that website among its many uses.\n" +
                "Usage Data refers to data collected automatically, either\n" +
                "generated by the use of the Service or from the Service\n" +
                "infrastructure itself (for example, the duration of a page visit).\n" +
                "Collecting and Using Your Personal Data Types of Data\n" +
                "Collected Personal Data While using Our Service, We may\n" +
                "ask You to provide Us with certain personally identifiable\n" +
                "information that can be used to contact or identify You.\n" +
                "Personally identifiable information may include, but is not\n" +
                "limited to:\n" +
                "Email address First name and last name Phone number\n" +
                "Usage Data Usage Data Usage Data is collected\n" +
                "automatically when using the Service.\n" +
                "Usage Data may include information such as Your Device’s\n" +
                "Internet Protocol address (e.g. IP address), browser type,\n" +
                "browser version, the pages of our Service that You visit, the\n" +
                "time and date of Your visit, the time spent on those pages,\n" +
                "unique device identifiers and other diagnostic data.\n" +
                "When You access the Service by or through a mobile device,\n" +
                "We may collect certain information automatically, including,\n" +
                "but not limited to, the type of mobile device You use, Your\n" +
                "mobile device unique ID, the IP address of Your mobile\n" +
                "device, Your mobile operating system, the type of mobile\n" +
                "Internet browser You use, unique device identifiers and other\n" +
                "diagnostic data.\n" +
                "We may also collect information that Your browser sends\n" +
                "whenever You visit our Service or when You access the\n" +
                "Service by or through a mobile device.\n" +
                "Tracking Technologies and Cookies We use Cookies and\n" +
                "similar tracking technologies to track the activity on Our\n" +
                "Service and store certain information. Tracking technologies\n" +
                "used are beacons, tags, and scripts to collect and track\n" +
                "information and to improve and analyze Our Service.\n" +
                "You can instruct Your browser to refuse all Cookies or to\n" +
                "indicate when a Cookie is being sent. However, if You do not\n" +
                "accept Cookies, You may not be able to use some parts of our\n" +
                "Service.\n" +
                "Cookies can be “Persistent” or “Session” Cookies. Persistent\n" +
                "Cookies remain on your personal computer or mobile device\n" +
                "when You go offline, while Session Cookies are deleted as\n" +
                "soon as You close your web browser.\n" +
                "We use both session and persistent Cookies for the\n" +
                "purposes set out below:\n" +
                "Necessary / Essential CookiesType: Session\n" +
                "CookiesAdministered by: UsPurpose: These Cookies are\n" +
                "essential to provide You with services available through the\n" +
                "Website and to enable You to use some of its features. They\n" +
                "help to authenticate users and prevent fraudulent use of user\n" +
                "accounts. Without these Cookies, the services that You have\n" +
                "asked for cannot be provided, and We only use these Cookies\n" +
                "to provide You with those services. Cookies Policy / Notice\n" +
                "Acceptance CookiesType: Persistent CookiesAdministered\n" +
                "by: UsPurpose: These Cookies identify if users have accepted\n" +
                "the use of cookies on the Website. Functionality CookiesType:\n" +
                "Persistent CookiesAdministered by: UsPurpose: These\n" +
                "Cookies allow us to remember choices You make when You\n" +
                "use the Website, such as remembering your login details or\n" +
                "language preference. The purpose of these Cookies is to\n" +
                "provide You with a more personal experience and to avoid\n" +
                "You having to re-enter your preferences every time You use\n" +
                "the Website. For more information about the cookies we use\n" +
                "and your choices regarding cookies, please visit our Cookies\n" +
                "Policy.\n" +
                "Use of Your Personal Data The Company may use\n" +
                "Personal Data for the following purposes:\n" +
                "To provide and maintain our Service, including to monitor the\n" +
                "usage of our Service. To manage Your Account: to manage\n" +
                "Your registration as a user of the Service. The Personal Data\n" +
                "You provide can give You access to different functionalities of\n" +
                "the Service that are available to You as a registered user. For\n" +
                "the performance of a contract: the development, compliance\n" +
                "and undertaking of the purchase contract for the products,\n" +
                "items or services You have purchased or of any other contract\n" +
                "with Us through the Service. To contact You: To contact You\n" +
                "by email, telephone calls, SMS, or other equivalent forms of\n" +
                "electronic communication, such as a mobile application’s\n" +
                "push notifications regarding updates or informative\n" +
                "communications related to the functionalities, products or\n" +
                "contracted services, including the security updates, when\n" +
                "necessary or reasonable for their implementation. To provide\n" +
                "You with news, special offers and general information about\n" +
                "other goods, services and events which we offer that are\n" +
                "similar to those that you have already purchased or enquired\n" +
                "about unless You have opted not to receive such information.\n" +
                "To manage Your requests: To attend and manage Your\n" +
                "requests to Us. We may share your personal information in\n" +
                "the following situations:\n" +
                "With Service Providers: We may share Your personal\n" +
                "information with Service Providers to monitor and analyze the\n" +
                "use of our Service, to show advertisements to You to help\n" +
                "support and maintain Our Service, to contact You, to advertise\n" +
                "on third party websites to You after You visited our Service or\n" +
                "for payment processing.\n" +
                "For Business transfers: We may share or transfer Your\n" +
                "personal information in connection with, or during negotiations\n" +
                "of, any merger, sale of Company assets, financing, or\n" +
                "acquisition of all or a portion of our business to another\n" +
                "company.\n" +
                "With Affiliates: We may share Your information with Our\n" +
                "affiliates, in which case we will require those affiliates to honor\n" +
                "this Privacy Policy. Affiliates include Our parent company and\n" +
                "any other subsidiaries, joint venture partners or other\n" +
                "companies that We control or that are under common control\n" +
                "with Us.\n" +
                "With Business partners: We may share Your information with\n" +
                "Our business partners to offer You certain products, services\n" +
                "or promotions.\n" +
                "With other users: when You share personal information or\n" +
                "otherwise interact in the public areas with other users, such\n" +
                "information may be viewed by all users and may be publicly\n" +
                "distributed outside. If You interact with other users or register\n" +
                "through a Third-Party Social Media Service, Your contacts on\n" +
                "the Third-Party Social Media Service may see You name,\n" +
                "profile, pictures and description of Your activity. Similarly,\n" +
                "other users will be able to view descriptions of Your activity,\n" +
                "communicate with You and view Your profile. Retention of\n" +
                "Your Personal Data\n" +
                "The Company will retain Your Personal Data only for as long\n" +
                "as is necessary for the purposes set out in this Privacy Policy.\n" +
                "We will retain and use Your Personal Data to the extent\n" +
                "necessary to comply with our legal obligations (for example, if\n" +
                "we are required to retain your data to comply with applicable\n" +
                "laws), resolve disputes, and enforce our legal agreements\n" +
                "and policies.\n" +
                "The Company will also retain Usage Data for internal analysis\n" +
                "purposes. Usage Data is generally retained for a shorter\n" +
                "period of time, except when this data is used to strengthen the\n" +
                "security or to improve the functionality of Our Service, or We\n" +
                "are legally obligated to retain this data for longer time periods.\n" +
                "Transfer of Your Personal Data Your information, including\n" +
                "Personal Data, is processed at the Company’s operating\n" +
                "offices and in any other places where the parties involved in\n" +
                "the processing are located. It means that this information may\n" +
                "be transferred to — and maintained on — computers located\n" +
                "outside of Your state, province, country or other governmental\n" +
                "jurisdiction where the data protection laws may differ than\n" +
                "those from Your jurisdiction.\n" +
                "Your consent to this Privacy Policy followed by Your\n" +
                "submission of such information represents Your agreement to\n" +
                "that transfer.\n" +
                "The Company will take all steps reasonably necessary to\n" +
                "ensure that Your data is treated securely and in accordance\n" +
                "with this Privacy Policy and no transfer of Your Personal Data\n" +
                "will take place to an organization or a country unless there are\n" +
                "adequate controls in place including the security of Your data\n" +
                "and other personal information.\n" +
                "Disclosure of Your Personal Data Business Transactions If the\n" +
                "Company is involved in a merger, acquisition or asset sale,\n" +
                "Your Personal Data may be transferred. We will provide notice\n" +
                "before Your Personal Data is transferred and becomes\n" +
                "subject to a different Privacy Policy.\n" +
                "Law enforcement Under certain circumstances, the Company\n" +
                "may be required to disclose Your Personal Data if required to\n" +
                "do so by law or in response to valid requests by public\n" +
                "authorities (e.g. a court or a government agency).\n" +
                "Other legal requirements The Company may disclose Your\n" +
                "Personal Data in the good faith belief that such action is\n" +
                "necessary to:\n" +
                "Comply with a legal obligation Protect and defend the rights or\n" +
                "property of the Company Prevent or investigate possible\n" +
                "wrongdoing in connection with the Service Protect the\n" +
                "personal safety of Users of the Service or the public Protect\n" +
                "against legal liability Security of Your Personal Data The\n" +
                "security of Your Personal Data is important to Us, but\n" +
                "remember that no method of transmission over the Internet, or\n" +
                "method of electronic storage is 100% secure. While We strive\n" +
                "to use commercially acceptable means to protect Your\n" +
                "Personal Data, We cannot guarantee its absolute security.\n" +
                "Children’s Privacy Our Service does not address anyone\n" +
                "under the age of 13. We do not knowingly collect personally\n" +
                "identifiable information from anyone under the age of 13. If\n" +
                "You are a parent or guardian and You are aware that Your\n" +
                "child has provided Us with Personal Data, please contact Us.\n" +
                "If We become aware that We have collected Personal Data\n" +
                "from anyone under the age of 13 without verification of\n" +
                "parental consent, We take steps to remove that information\n" +
                "from Our servers.\n" +
                "We also may limit how We collect, use, and store some of the\n" +
                "information of Users between 13 and 18 years old. In some\n" +
                "cases, this means We will be unable to provide certain\n" +
                "functionality of the Service to these users.\n" +
                "If We need to rely on consent as a legal basis for processing\n" +
                "Your information and Your country requires consent from a\n" +
                "parent, We may require Your parent’s consent before We\n" +
                "collect and use that information.\n" +
                "Links to Other Websites Our Service may contain links to\n" +
                "other websites that are not operated by Us. If You click on a\n" +
                "third party link, You will be directed to that third party’s site.\n" +
                "We strongly advise You to review the Privacy Policy of every\n" +
                "site You visit.\n" +
                "We have no control over and assume no responsibility for the\n" +
                "content, privacy policies or practices of any third party sites or\n" +
                "services.\n" +
                "Changes to this Privacy Policy We may update our Privacy\n" +
                "Policy from time to time. We will notify You of any changes by\n" +
                "posting the new Privacy Policy on this page.\n" +
                "We will let You know via email and/or a prominent notice on\n" +
                "Our Service, prior to the change becoming effective and\n" +
                "update the “Last updated” date at the top of this Privacy\n" +
                "Policy.\n" +
                "You are advised to review this Privacy Policy periodically for\n" +
                "any changes. Changes to this Privacy Policy are effective\n" +
                "when they are posted on this page.\n" +
                "Contact Us If you have any questions about this Privacy\n" +
                "Policy, You can contact us :\n" +
                "By email: hithesh@vidhyasoft.com"



    }

}